service: Lightspeed-Moneybird-integration

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    LIGHTSPEED_CLIENT: ${env:LIGHTSPEED_CLIENT}
    LIGHTSPEED_SECRET: ${env:LIGHTSPEED_SECRET}
    MONEYBIRD_CLIENT: ${env:MONEYBIRD_CLIENT}
    MONEYBIRD_SECRET: ${env:MONEYBIRD_SECRET}
    aws_access_key_id: ${env:aws_access_key_id}
    aws_secret_access_key: ${env:aws_secret_access_key}
  timeout: 300

package:
  exclude:
    - src/**
    - node_modules/**
    - public/**
    - .git/**
    - .cache/**
  include:
    - functions/integration-accountancy.js
    - functions/integration-report.js
    - functions/algorithm-reorder.js
    - src/data/**

functions:
  automatedInvoice:
    handler: functions/integration-accountancy.handler
    events:
      - schedule: "cron(0 21 * * ? *)"
  dayReport:
    handler: functions/integration-report.handler
    events:
      - schedule: "cron(0 17 * * ? *)"
  # automatedReorder:
  #   handler: functions/algorithm-reorder.handler
  #   events:
  #     - schedule:
  #         rate: rate(1 hour)
  #         input:
  #           datatype: 'sales'
  automatedRead:
    handler: functions/algorithm-read.handler
    events:
      # - schedule:
      #     rate: "cron(0 3 * * ? *)"
      #     input:
      #       datatype: 'sales'
      # - schedule:
      #     rate: "cron(5 3 * * ? *)"
      #     input:
      #       datatype: 'items'
      - schedule:
          rate: "rate(1 hour)"
          input:
            datatype:
              queryStringParameters: 'categories'
